server:
  port: 8001

spring:
  application:
    name: cloudalibaba-sentinel-provider
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
      datasource:
        flow:  #这里命名随意，见名知意即可
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: flow #规则类型，取值见org.springframework.cloud.alibaba.sentinel.datasource.RuleType

management:
  endpoints:
    web:
      exposure:
        include: '*'
