server:
  port: 8001

spring:
  application:
    name: springcloud-eureka-provider   #微服务名称，集群下相同提供者微服务名称相同

#配置eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #单机版
  instance:
    instance-id: 8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
