server:
  port: 7001


eureka:
  instance:
    hostname: eureka7001.com  #注册中心这个没啥用，只要不其他注册中心的重复就行
  client:
    register-with-eureka: false  #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #服务连接地址：注册中心单机版写自己的地址或者不写（域名访问需要映射），集群版写别的注册中心地址。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   #单机版本
      #defaultZone: http://eureka7002.com:7002/eureka/      #集群版，就是相互注册相互守望（7001注册7002）
  server:
    #我保护机制，默认开启。自我保护机制中，下面规定时间内，如果服务不可用了也不会被注销。属于AP分支
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000 #等待时间，单位毫秒
