#打开logo，其中spring.main.xxx有很多配置方式
spring.main.banner-mode = console
#指定配置类
spring.main.sources=com.huangjiabin.springboot.Application
#不允许spring bean定义名字覆盖
spring.main.allow-bean-definition-overriding=true
#是否延迟初始化，用到才创建bean
spring.main.lazy-initialization=false

#启动时输入日志
spring.main.log-startup-info=true

#是否注册shutdown回调钩子
spring.main.register-shutdown-hook=true

#springboot项目类型，none=java reactive=响应式 servlet=web
spring.main.web-application-type=none


#指定加密解密密钥key,随便写。
jasypt.encryptor.password=123%advadsabu
jasypt.encryptor.property.prefix=ENC(
jasypt.encryptor.property.suffix=)
