<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <parent>
    <artifactId>001-maven-parent</artifactId>
    <groupId>com.huangjiabin</groupId>
    <version>1.0-SNAPSHOT</version>
    <relativePath>../001-maven-parent/pom.xml</relativePath>
  </parent>
  <modelVersion>4.0.0</modelVersion>

  <artifactId>003-maven-web</artifactId>

  <!--告诉父模块自己需要的依赖，不用添加版本号了，前提父工程有
      如果子模块自己添加版本了就不继承父工程了
  -->
  <dependencies>
    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
    </dependency>
  </dependencies>

</project>
