server:
  port: 80

spring:
  application:
    name: springcloud-hystrix-consumer

#设置feign客户端超时时间
feign:
  client:
    config:
      SPRINGCLOUD-EUREKA-PROVIDER:    #作用域 1、针对某个服务的配置，这里是服务名称
      #default:                       #作用域 2、全局配制
        readTimeout: 5000     #指的是建立连接后从服务器读取到可用资源所用的时间
        connectTimeout: 5000  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
        loggerLevel: FULL     #配置feign日志输出级别，默认不显示
  #hystrix:
    #enabled: true  #开启feign支持hystrix，消费者service层开启降级需要（controller层开启不需要）。加了设置的读取时间会失效，会超1s超时

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka    #集群版
  instance:
    instance-id: 80
logging:
  level:
    com.huangjiabin.springcloud.service.feign.ProviderService: debug
