#springboot主核心配置文件
#激活使用的配置文件,换环境的话只需要更改主核心配置文件，这里的是文件名application-什么就是什么
#换成.yml也一样，不过是展现形式不一样
spring.profiles.active=dev
#自定义配置
school.name=Chengdu College of UESTC
school.wbsit=www.cduest.cn

#自定义配置映射到对象,必须要有同一的前缀如：student
student.name=徐凤年
student.wbsit=no
#注意，这里要是用user.name的话，后台调用是掉的‘不是我’，计算机的名字，不是这里配的名字尼古丁
user1.name=尼古丁
user1.age=-1

#配置文件玩法
my.secret=${random.value}
my.number=${random.int}
my.bignumber=${random.long}
my.uuid=${random.uuid}
my.number.less=${random.int(10)}
my.number.in.range=${random.int(1024,65536)}

#配置文件玩法，占位符
my.name=huang
my。desc=${student.name} is a shuige

#单位换算
#30，PT30、30s都是等效的
#ns纳秒，us微妙，ms毫秒，s秒，m分钟，H小时，d天，w周，m月，y年

#DataSize类型单位换算
#若要指定10MB的缓存区大小，则10和10MB都是等效的
#256个字节的大小阈值可以指定为256或256B
#B for bytes
#KB for kilobytes
#MB for megabytes
#GB for gigabytes
#TB for terabytes
#比如：server.tomcat.max-swallow-size=2048KB/2048

