server:
  port: 8001

spring:
  application:
    name: springcloud-eureka-provider   #微服务名称，集群下相同提供者微服务名称相同
  datasource:   #配置数据库
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1220.dbggl.mysql

#配置eureka
eureka:
  client:
    register-with-eureka: true  #表示是否将自己注册进eureka服务，默认为true
    #是否从Eureka Server抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true 才能配合ribbon 使用负裁均衡
    fetch-registry: true
    service-url:
      #服务连接地址，客户端（提供者和消费者）写要注册的中心地址的地址
      #defaultZone: http://eureka7001.com:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/ #集群版
  instance:
    instance-id: 8001  #实例id，用于区分客户端节点
    prefer-ip-address: true #默认为false：有hostname则显示，没有则显示计算机名字如bin；为true：有ip-address则显示，没有则显示第一个非回环ip地址如：192.168.205.1
    hostname: localhost   #写实际的，影响消费者调用
    ip-address: 127.0.0.1 #写实际的，影响消费者调用
    lease-renewal-interval-in-seconds: 3 #客户端（消费者和提供者）向服务端（注册中心）发送心跳间隔时间，默认30秒
    lease-expiration-duration-in-seconds: 10 #服务端（注册中心）等待心跳时间。注册中心关闭了自我保护机制的话，等待时间内没收到心跳，就会将该服务注销，默认90秒

#配置mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.huangjiabin.entity    # 所有Entity别名类所在包
